/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg2210010581_annisa_uts.keuanganpribadi;

import java.awt.Color;
import java.awt.Font;
import javax.swing.*;
import java.awt.Dimension;
/**
 *
 * @author Annisa
 * 2210010581
 */
public class FrameHalamanAwal extends javax.swing.JFrame {

    /**
     * Creates new form FrameHalamanAwal
     */
    public FrameHalamanAwal() {
        initComponents();
        initComponentss();
    }
    
     // Set window title
       private void initComponentss() {
        setTitle("Selamat Datang Annisa");
        
     
        // Configure window
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setBackground(new Color(255, 192, 203)); // Pink background
        
        // Configure labels
        lblJudul.setText("Aplikasi Keuangan Pribadi Annisa");
        lblJudul.setFont(new Font("Arial", Font.BOLD, 18));
        lblJudul.setHorizontalAlignment(SwingConstants.CENTER);
        
        lblKelas.setText("Kelas 5C Reguler Pagi Banjarmasin");
        lblKelas.setFont(new Font("Arial", Font.PLAIN, 14));
        lblKelas.setHorizontalAlignment(SwingConstants.CENTER);
        

        
        // Layout setup
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.CENTER)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.CENTER)
                    .addComponent(lblJudul)
                    .addComponent(lblKelas))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        
        layout.setVerticalGroup(
            layout.createSequentialGroup()
            .addGap(40)
            .addComponent(lblJudul)
            .addGap(50)
            .addComponent(lblKelas)
            .addGap(40)
            .addContainerGap(40, Short.MAX_VALUE)
        );
        
        // Set window size and center it
        setPreferredSize(new Dimension(400, 300));
        pack();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        btnMulaiAplikasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setText("APLIKASI KEUANGAN PRIBADI ANNISA");

        lblKelas.setText("KELAS 5C REGULER PAGI BANJARMASIN");

        btnMulaiAplikasi.setText("Mulai Aplikasi");
        btnMulaiAplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulaiAplikasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblJudul)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(102, 102, 102)
                            .addComponent(lblKelas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnMulaiAplikasi)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblJudul)
                .addGap(56, 56, 56)
                .addComponent(lblKelas)
                .addGap(36, 36, 36)
                .addComponent(btnMulaiAplikasi)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMulaiAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulaiAplikasiActionPerformed
          new AplikasiUtama().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnMulaiAplikasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameHalamanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameHalamanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameHalamanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameHalamanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameHalamanAwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMulaiAplikasi;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKelas;
    // End of variables declaration//GEN-END:variables
}
